### ISSUE TITLE
Feature Request - Add Alpine Lakes / Mountain Lakes - Allow Lake to spawn above sea level

### ISSUE THREAD

**Issue by seeditch** [racoonman2/ReTerraForged#94] opened 2024-07-29 06:26 UTC
It can be very nice scenery with lake above elevation sea level. I think thes feature will make the mod be more realistic and better than all mod for terrain already. Because like real life water do not spawn in sea level, and can be above sometime. If you know how to create something similar,maybe use with local sea level, please try! I think it can be great ideas.

**Comment by racoonman2** [comment] 2024-07-29 22:27
this is a duplicate of this https://github.com/racoonman2/ReTerraForged/issues/55

**Closed as not planned by racoonman2** 2024-07-29 22:27 UTC

**Comment by seeditch** [comment] 2024-07-29 22:34
Hi it is not exactly the same, that one was for rivers. I am talking of lake that takes local sea level altitude when generating. Please before discarding idea i think this would be great addition, if you are able to do it would be very grate. Sorry for saying same things but I hope you consider sometimes.

**Comment by racoonman2** [comment] 2024-07-30 13:21
elevated lakes are being included as part of the 3d rivers, ill change the issue name to better reflect that
